packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - better-sqlite3

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi
