/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeBasesIndexRouteImport } from './routes/knowledge-bases/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as MyKnowledgeBasesRouteImport } from './routes/my/knowledge-bases'
import { Route as MyCharactersRouteImport } from './routes/my/characters'
import { Route as KnowledgeBasesIdRouteImport } from './routes/knowledge-bases/$id'
import { Route as CharactersIdRouteImport } from './routes/characters/$id'
import { Route as CharactersIdDetailTestRouteImport } from './routes/characters/$id.detail-test'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBasesIndexRoute = KnowledgeBasesIndexRouteImport.update({
  id: '/knowledge-bases/',
  path: '/knowledge-bases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyKnowledgeBasesRoute = MyKnowledgeBasesRouteImport.update({
  id: '/my/knowledge-bases',
  path: '/my/knowledge-bases',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCharactersRoute = MyCharactersRouteImport.update({
  id: '/my/characters',
  path: '/my/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBasesIdRoute = KnowledgeBasesIdRouteImport.update({
  id: '/knowledge-bases/$id',
  path: '/knowledge-bases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdRoute = CharactersIdRouteImport.update({
  id: '/characters/$id',
  path: '/characters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdDetailTestRoute = CharactersIdDetailTestRouteImport.update({
  id: '/detail-test',
  path: '/detail-test',
  getParentRoute: () => CharactersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/characters/$id': typeof CharactersIdRouteWithChildren
  '/knowledge-bases/$id': typeof KnowledgeBasesIdRoute
  '/my/characters': typeof MyCharactersRoute
  '/my/knowledge-bases': typeof MyKnowledgeBasesRoute
  '/characters/': typeof CharactersIndexRoute
  '/knowledge-bases/': typeof KnowledgeBasesIndexRoute
  '/characters/$id/detail-test': typeof CharactersIdDetailTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/characters/$id': typeof CharactersIdRouteWithChildren
  '/knowledge-bases/$id': typeof KnowledgeBasesIdRoute
  '/my/characters': typeof MyCharactersRoute
  '/my/knowledge-bases': typeof MyKnowledgeBasesRoute
  '/characters': typeof CharactersIndexRoute
  '/knowledge-bases': typeof KnowledgeBasesIndexRoute
  '/characters/$id/detail-test': typeof CharactersIdDetailTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/characters/$id': typeof CharactersIdRouteWithChildren
  '/knowledge-bases/$id': typeof KnowledgeBasesIdRoute
  '/my/characters': typeof MyCharactersRoute
  '/my/knowledge-bases': typeof MyKnowledgeBasesRoute
  '/characters/': typeof CharactersIndexRoute
  '/knowledge-bases/': typeof KnowledgeBasesIndexRoute
  '/characters/$id/detail-test': typeof CharactersIdDetailTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/settings'
    | '/characters/$id'
    | '/knowledge-bases/$id'
    | '/my/characters'
    | '/my/knowledge-bases'
    | '/characters/'
    | '/knowledge-bases/'
    | '/characters/$id/detail-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/settings'
    | '/characters/$id'
    | '/knowledge-bases/$id'
    | '/my/characters'
    | '/my/knowledge-bases'
    | '/characters'
    | '/knowledge-bases'
    | '/characters/$id/detail-test'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/settings'
    | '/characters/$id'
    | '/knowledge-bases/$id'
    | '/my/characters'
    | '/my/knowledge-bases'
    | '/characters/'
    | '/knowledge-bases/'
    | '/characters/$id/detail-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  CharactersIdRoute: typeof CharactersIdRouteWithChildren
  KnowledgeBasesIdRoute: typeof KnowledgeBasesIdRoute
  MyCharactersRoute: typeof MyCharactersRoute
  MyKnowledgeBasesRoute: typeof MyKnowledgeBasesRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  KnowledgeBasesIndexRoute: typeof KnowledgeBasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-bases/': {
      id: '/knowledge-bases/'
      path: '/knowledge-bases'
      fullPath: '/knowledge-bases/'
      preLoaderRoute: typeof KnowledgeBasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/knowledge-bases': {
      id: '/my/knowledge-bases'
      path: '/my/knowledge-bases'
      fullPath: '/my/knowledge-bases'
      preLoaderRoute: typeof MyKnowledgeBasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/characters': {
      id: '/my/characters'
      path: '/my/characters'
      fullPath: '/my/characters'
      preLoaderRoute: typeof MyCharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-bases/$id': {
      id: '/knowledge-bases/$id'
      path: '/knowledge-bases/$id'
      fullPath: '/knowledge-bases/$id'
      preLoaderRoute: typeof KnowledgeBasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$id': {
      id: '/characters/$id'
      path: '/characters/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof CharactersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$id/detail-test': {
      id: '/characters/$id/detail-test'
      path: '/detail-test'
      fullPath: '/characters/$id/detail-test'
      preLoaderRoute: typeof CharactersIdDetailTestRouteImport
      parentRoute: typeof CharactersIdRoute
    }
  }
}

interface CharactersIdRouteChildren {
  CharactersIdDetailTestRoute: typeof CharactersIdDetailTestRoute
}

const CharactersIdRouteChildren: CharactersIdRouteChildren = {
  CharactersIdDetailTestRoute: CharactersIdDetailTestRoute,
}

const CharactersIdRouteWithChildren = CharactersIdRoute._addFileChildren(
  CharactersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  CharactersIdRoute: CharactersIdRouteWithChildren,
  KnowledgeBasesIdRoute: KnowledgeBasesIdRoute,
  MyCharactersRoute: MyCharactersRoute,
  MyKnowledgeBasesRoute: MyKnowledgeBasesRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  KnowledgeBasesIndexRoute: KnowledgeBasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
