/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as KnowledgeBasesRouteImport } from './routes/knowledge-bases'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeBasesIdRouteImport } from './routes/knowledge-bases.$id'
import { Route as CharactersIdRouteImport } from './routes/characters.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBasesRoute = KnowledgeBasesRouteImport.update({
  id: '/knowledge-bases',
  path: '/knowledge-bases',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBasesIdRoute = KnowledgeBasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KnowledgeBasesRoute,
} as any)
const CharactersIdRoute = CharactersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CharactersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRouteWithChildren
  '/knowledge-bases': typeof KnowledgeBasesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/characters/$id': typeof CharactersIdRoute
  '/knowledge-bases/$id': typeof KnowledgeBasesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRouteWithChildren
  '/knowledge-bases': typeof KnowledgeBasesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/characters/$id': typeof CharactersIdRoute
  '/knowledge-bases/$id': typeof KnowledgeBasesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters': typeof CharactersRouteWithChildren
  '/knowledge-bases': typeof KnowledgeBasesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/characters/$id': typeof CharactersIdRoute
  '/knowledge-bases/$id': typeof KnowledgeBasesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters'
    | '/knowledge-bases'
    | '/profile'
    | '/settings'
    | '/characters/$id'
    | '/knowledge-bases/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters'
    | '/knowledge-bases'
    | '/profile'
    | '/settings'
    | '/characters/$id'
    | '/knowledge-bases/$id'
  id:
    | '__root__'
    | '/'
    | '/characters'
    | '/knowledge-bases'
    | '/profile'
    | '/settings'
    | '/characters/$id'
    | '/knowledge-bases/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersRoute: typeof CharactersRouteWithChildren
  KnowledgeBasesRoute: typeof KnowledgeBasesRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-bases': {
      id: '/knowledge-bases'
      path: '/knowledge-bases'
      fullPath: '/knowledge-bases'
      preLoaderRoute: typeof KnowledgeBasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-bases/$id': {
      id: '/knowledge-bases/$id'
      path: '/$id'
      fullPath: '/knowledge-bases/$id'
      preLoaderRoute: typeof KnowledgeBasesIdRouteImport
      parentRoute: typeof KnowledgeBasesRoute
    }
    '/characters/$id': {
      id: '/characters/$id'
      path: '/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof CharactersIdRouteImport
      parentRoute: typeof CharactersRoute
    }
  }
}

interface CharactersRouteChildren {
  CharactersIdRoute: typeof CharactersIdRoute
}

const CharactersRouteChildren: CharactersRouteChildren = {
  CharactersIdRoute: CharactersIdRoute,
}

const CharactersRouteWithChildren = CharactersRoute._addFileChildren(
  CharactersRouteChildren,
)

interface KnowledgeBasesRouteChildren {
  KnowledgeBasesIdRoute: typeof KnowledgeBasesIdRoute
}

const KnowledgeBasesRouteChildren: KnowledgeBasesRouteChildren = {
  KnowledgeBasesIdRoute: KnowledgeBasesIdRoute,
}

const KnowledgeBasesRouteWithChildren = KnowledgeBasesRoute._addFileChildren(
  KnowledgeBasesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersRoute: CharactersRouteWithChildren,
  KnowledgeBasesRoute: KnowledgeBasesRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
