// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ApiResponse[AuthOut]
 */
export type ApiResponseAuthOut = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * 响应数据
     */
    data?: AuthOut | null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * ApiResponse[CharacterDetailOut]
 */
export type ApiResponseCharacterDetailOut = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * 响应数据
     */
    data?: CharacterDetailOut | null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * ApiResponse[ChatOut]
 */
export type ApiResponseChatOut = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * 响应数据
     */
    data?: ChatOut | null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * ApiResponse[KnowledgeBaseOut]
 */
export type ApiResponseKnowledgeBaseOut = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * 响应数据
     */
    data?: KnowledgeBaseOut | null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * ApiResponse[KnowledgeDocumentOut]
 */
export type ApiResponseKnowledgeDocumentOut = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * 响应数据
     */
    data?: KnowledgeDocumentOut | null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * ApiResponse[LlmConfigOut]
 */
export type ApiResponseLlmConfigOut = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * 响应数据
     */
    data?: LlmConfigOut | null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * ApiResponse[LoginOut]
 */
export type ApiResponseLoginOut = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * 响应数据
     */
    data?: LoginOut | null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * ApiResponse[NoneType]
 */
export type ApiResponseNoneType = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * Data
     *
     * 响应数据
     */
    data?: null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * ApiResponse[PaginatedResponse[CharacterListItemOut]]
 */
export type ApiResponsePaginatedResponseCharacterListItemOut = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * 响应数据
     */
    data?: PaginatedResponseCharacterListItemOut | null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * ApiResponse[PaginatedResponse[ChatMessageOut]]
 */
export type ApiResponsePaginatedResponseChatMessageOut = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * 响应数据
     */
    data?: PaginatedResponseChatMessageOut | null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * ApiResponse[PaginatedResponse[ChatOut]]
 */
export type ApiResponsePaginatedResponseChatOut = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * 响应数据
     */
    data?: PaginatedResponseChatOut | null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * ApiResponse[PaginatedResponse[KnowledgeBaseOut]]
 */
export type ApiResponsePaginatedResponseKnowledgeBaseOut = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * 响应数据
     */
    data?: PaginatedResponseKnowledgeBaseOut | null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * ApiResponse[PaginatedResponse[UserOut]]
 */
export type ApiResponsePaginatedResponseUserOut = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * 响应数据
     */
    data?: PaginatedResponseUserOut | null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * ApiResponse[TokenOut]
 */
export type ApiResponseTokenOut = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * 响应数据
     */
    data?: TokenOut | null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * ApiResponse[UserDetailOut]
 */
export type ApiResponseUserDetailOut = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * 响应数据
     */
    data?: UserDetailOut | null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * ApiResponse[UserOut]
 */
export type ApiResponseUserOut = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * 响应数据
     */
    data?: UserOut | null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * ApiResponse[UserPublicOut]
 */
export type ApiResponseUserPublicOut = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * 响应数据
     */
    data?: UserPublicOut | null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * ApiResponse[list[KnowledgeBaseOut]]
 */
export type ApiResponseListKnowledgeBaseOut = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * Data
     *
     * 响应数据
     */
    data?: Array<KnowledgeBaseOut> | null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * ApiResponse[list[LlmConfigOut]]
 */
export type ApiResponseListLlmConfigOut = {
    /**
     * Status
     *
     * 响应状态
     */
    status?: string;
    /**
     * Data
     *
     * 响应数据
     */
    data?: Array<LlmConfigOut> | null;
    /**
     * Message
     *
     * 响应信息
     */
    message?: string;
    /**
     * Error Code
     *
     * 内部错误码
     */
    error_code?: string | null;
    /**
     * Timestamp
     *
     * 响应时间戳
     */
    timestamp?: number;
};

/**
 * AuthOut
 *
 * 认证响应体
 */
export type AuthOut = {
    /**
     * Userid
     *
     * 用户ID
     */
    userId: string;
    /**
     * Identifier
     *
     * 识别码
     */
    identifier: string;
    /**
     * Identitytype
     *
     * 认证类型
     */
    identityType: string;
    /**
     * Status
     *
     * 用户状态
     */
    status: 'active' | 'inactive' | 'banned';
    /**
     * Createdat
     *
     * 创建时间
     */
    createdAt: string;
    /**
     * Updatedat
     *
     * 更新时间
     */
    updatedAt: string;
};

/**
 * BindKnowledgeBaseIn
 *
 * 为角色绑定知识库
 */
export type BindKnowledgeBaseIn = {
    /**
     * Knowledgebaseid
     *
     * 知识库ID
     */
    knowledgeBaseId: string;
};

/**
 * Body_upload_document
 */
export type BodyUploadDocument = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * ChangePasswordIn
 */
export type ChangePasswordIn = {
    /**
     * Oldpassword
     *
     * 旧密码
     */
    oldPassword: string;
    /**
     * Newpassword
     *
     * 新密码
     */
    newPassword: string;
};

/**
 * CharacterCreateIn
 *
 * 创建角色请求体
 */
export type CharacterCreateIn = {
    /**
     * Name
     *
     * 角色名称
     */
    name: string;
    /**
     * Avatar
     *
     * 角色头像
     */
    avatar?: string | null;
    /**
     * Bio
     *
     * 角色个性签名
     */
    bio?: string | null;
    /**
     * Tags
     *
     * 角色标签
     */
    tags?: Array<string>;
    /**
     * Ispublic
     *
     * 是否公开
     */
    isPublic?: boolean;
    /**
     * Status
     *
     * 角色状态
     */
    status?: 'draft' | 'active' | 'pending' | 'deleted' | 'banned';
    /**
     * Systemprompt
     *
     * 系统提示词
     */
    systemPrompt?: string;
    /**
     * Baseconfig
     *
     * LLM生成参数
     */
    baseConfig?: {
        [key: string]: unknown;
    };
};

/**
 * CharacterDetailOut
 *
 * 角色详情响应体
 */
export type CharacterDetailOut = {
    /**
     * Name
     *
     * 角色名称
     */
    name: string;
    /**
     * Avatar
     *
     * 角色头像
     */
    avatar?: string | null;
    /**
     * Bio
     *
     * 角色个性签名
     */
    bio?: string | null;
    /**
     * Tags
     *
     * 角色标签
     */
    tags?: Array<string>;
    /**
     * Ispublic
     *
     * 是否公开
     */
    isPublic?: boolean;
    /**
     * Status
     *
     * 角色状态
     */
    status?: 'draft' | 'active' | 'pending' | 'deleted' | 'banned';
    /**
     * Id
     *
     * 角色ID
     */
    id: string;
    /**
     * Authorid
     *
     * 作者ID
     */
    authorId: string;
    /**
     * Systemprompt
     *
     * 系统提示词
     */
    systemPrompt?: string;
    /**
     * Baseconfig
     *
     * LLM生成参数
     */
    baseConfig?: {
        [key: string]: unknown;
    };
    /**
     * Favoritecount
     *
     * 总收藏数
     */
    favoriteCount: number;
    /**
     * Chatcount
     *
     * 聊天数
     */
    chatCount: number;
    /**
     * Isfavorited
     *
     * 当前用户是否已收藏
     */
    isFavorited?: boolean;
    /**
     * Createdat
     *
     * 创建时间
     */
    createdAt: string;
    /**
     * Updatedat
     *
     * 更新时间
     */
    updatedAt: string;
};

/**
 * CharacterListItemOut
 *
 * 角色列表响应体
 */
export type CharacterListItemOut = {
    /**
     * Name
     *
     * 角色名称
     */
    name: string;
    /**
     * Avatar
     *
     * 角色头像
     */
    avatar?: string | null;
    /**
     * Bio
     *
     * 角色个性签名
     */
    bio?: string | null;
    /**
     * Tags
     *
     * 角色标签
     */
    tags?: Array<string>;
    /**
     * Ispublic
     *
     * 是否公开
     */
    isPublic?: boolean;
    /**
     * Status
     *
     * 角色状态
     */
    status?: 'draft' | 'active' | 'pending' | 'deleted' | 'banned';
    /**
     * Id
     *
     * 角色ID
     */
    id: string;
    /**
     * Authorid
     *
     * 作者ID
     */
    authorId: string;
    /**
     * Favoritecount
     *
     * 总收藏数
     */
    favoriteCount: number;
    /**
     * Chatcount
     *
     * 聊天数
     */
    chatCount: number;
    /**
     * Isfavorited
     *
     * 当前用户是否已收藏
     */
    isFavorited?: boolean;
    /**
     * Createdat
     *
     * 创建时间
     */
    createdAt: string;
};

/**
 * CharacterUpdateIn
 *
 * 更新角色请求体（全字段可选）
 */
export type CharacterUpdateIn = {
    /**
     * Name
     *
     * 角色名称
     */
    name?: string | null;
    /**
     * Avatar
     *
     * 角色头像
     */
    avatar?: string | null;
    /**
     * Bio
     *
     * 角色个性签名
     */
    bio?: string | null;
    /**
     * Systemprompt
     *
     * 系统提示词
     */
    systemPrompt?: string | null;
    /**
     * Baseconfig
     *
     * LLM生成参数
     */
    baseConfig?: {
        [key: string]: unknown;
    } | null;
    /**
     * Tags
     *
     * 角色标签
     */
    tags?: Array<string> | null;
    /**
     * Ispublic
     *
     * 是否公开
     */
    isPublic?: boolean | null;
    /**
     * Status
     *
     * 角色状态
     */
    status?: 'draft' | 'active' | 'pending' | 'deleted' | 'banned' | null;
};

/**
 * ChatCreateIn
 *
 * 创建会话请求
 */
export type ChatCreateIn = {
    /**
     * Characterid
     *
     * 角色ID
     */
    characterId: string;
    /**
     * Title
     *
     * 会话标题
     */
    title?: string | null;
    /**
     * Llmconfigid
     *
     * 使用的用户模型配置ID
     */
    llmConfigId?: string | null;
    /**
     * Settings
     *
     * 会话级参数覆盖
     */
    settings?: {
        [key: string]: unknown;
    };
};

/**
 * ChatMessageCreateIn
 *
 * 发送消息请求
 */
export type ChatMessageCreateIn = {
    /**
     * Content
     *
     * 消息正文
     */
    content: string;
    /**
     * Contenttype
     *
     * 内容类型
     */
    contentType?: 'text' | 'image' | 'multimodal';
    /**
     * Parts
     *
     * 多模态内容块
     */
    parts?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Parentid
     *
     * 回复的上游消息ID
     */
    parentId?: string | null;
    /**
     * Attachments
     *
     * 附件元数据列表
     */
    attachments?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * ChatMessageOut
 *
 * 消息响应
 */
export type ChatMessageOut = {
    /**
     * Id
     *
     * 消息ID
     */
    id: string;
    /**
     * Chatid
     *
     * 会话ID
     */
    chatId: string;
    /**
     * Runid
     *
     * LangGraph run_id
     */
    runId?: string | null;
    /**
     * Parentid
     *
     * 上游消息ID
     */
    parentId?: string | null;
    /**
     * Role
     *
     * 消息角色
     */
    role: string;
    /**
     * Content
     *
     * 纯文本内容
     */
    content?: string | null;
    /**
     * Parts
     *
     * 多模态内容块
     */
    parts?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Contenttype
     *
     * 内容类型
     */
    contentType: string;
    /**
     * Status
     *
     * 消息状态
     */
    status: string;
    /**
     * Model
     *
     * LLM模型
     */
    model?: string | null;
    /**
     * Tokensused
     *
     * Token消耗
     */
    tokensUsed?: number | null;
    /**
     * Latencyms
     *
     * 生成耗时
     */
    latencyMs?: number | null;
    /**
     * Createdat
     *
     * 创建时间
     */
    createdAt: string;
    /**
     * Updatedat
     *
     * 更新时间
     */
    updatedAt: string;
};

/**
 * ChatOut
 *
 * 会话列表/详情响应
 */
export type ChatOut = {
    /**
     * Id
     *
     * 会话ID
     */
    id: string;
    /**
     * Userid
     *
     * 用户ID
     */
    userId: string;
    /**
     * Characterid
     *
     * 角色ID
     */
    characterId: string;
    /**
     * Title
     *
     * 会话标题
     */
    title?: string | null;
    /**
     * Status
     *
     * 会话状态
     */
    status: string;
    /**
     * Lastmessageat
     *
     * 最后消息时间
     */
    lastMessageAt?: string | null;
    /**
     * Messagecount
     *
     * 消息数
     */
    messageCount: number;
    /**
     * Contextwindow
     *
     * 上下文窗口
     */
    contextWindow: number;
    /**
     * Llmconfigid
     *
     * 使用的用户模型配置ID
     */
    llmConfigId?: string | null;
    /**
     * Settings
     *
     * 会话参数
     */
    settings?: {
        [key: string]: unknown;
    };
    /**
     * Createdat
     *
     * 创建时间
     */
    createdAt: string;
    /**
     * Updatedat
     *
     * 更新时间
     */
    updatedAt: string;
    /**
     * Ispinned
     *
     * 是否置顶
     */
    isPinned?: boolean;
};

/**
 * ChatUpdateIn
 *
 * 更新会话请求
 */
export type ChatUpdateIn = {
    /**
     * Title
     *
     * 会话标题
     */
    title?: string | null;
    /**
     * Status
     *
     * 会话状态
     */
    status?: 'active' | 'archived' | 'deleted' | null;
    /**
     * Llmconfigid
     *
     * 使用的用户模型配置ID
     */
    llmConfigId?: string | null;
    /**
     * Settings
     *
     * 会话级参数覆盖
     */
    settings?: {
        [key: string]: unknown;
    } | null;
};

/**
 * EmailRegisterIn
 *
 * 邮箱注册请求体
 */
export type EmailRegisterIn = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * EmailVerifyConfirmIn
 *
 * 验证邮箱请求体
 */
export type EmailVerifyConfirmIn = {
    /**
     * Email
     */
    email: string;
    /**
     * Otp
     *
     * 验证码
     */
    otp: string;
};

/**
 * EmailVerifyRequestIn
 *
 * 邮箱验证请求体
 */
export type EmailVerifyRequestIn = {
    /**
     * Email
     */
    email: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * KnowledgeBaseCreateIn
 *
 * 创建知识库
 */
export type KnowledgeBaseCreateIn = {
    /**
     * Name
     *
     * 知识库名称
     */
    name: string;
    /**
     * Description
     *
     * 描述
     */
    description?: string | null;
    /**
     * Ispublic
     *
     * 是否公开
     */
    isPublic?: boolean;
};

/**
 * KnowledgeBaseOut
 *
 * 知识库输出
 */
export type KnowledgeBaseOut = {
    /**
     * Id
     *
     * 知识库ID
     */
    id: string;
    /**
     * Authorid
     *
     * 作者ID
     */
    authorId: string;
    /**
     * Name
     *
     * 知识库名称
     */
    name: string;
    /**
     * Description
     *
     * 描述
     */
    description?: string | null;
    /**
     * Status
     *
     * 状态
     */
    status: string;
    /**
     * Ispublic
     *
     * 是否公开
     */
    isPublic: boolean;
    /**
     * Embeddingmodel
     *
     * 嵌入模型
     */
    embeddingModel: string;
    /**
     * Documentcount
     *
     * 文档数
     */
    documentCount: number;
    /**
     * Chunkcount
     *
     * 片段数
     */
    chunkCount: number;
    /**
     * Createdat
     *
     * 创建时间
     */
    createdAt: string;
    /**
     * Updatedat
     *
     * 更新时间
     */
    updatedAt: string;
};

/**
 * KnowledgeBaseUpdateIn
 *
 * 更新知识库
 */
export type KnowledgeBaseUpdateIn = {
    /**
     * Name
     *
     * 知识库名称
     */
    name?: string | null;
    /**
     * Description
     *
     * 描述
     */
    description?: string | null;
    /**
     * Ispublic
     *
     * 是否公开
     */
    isPublic?: boolean | null;
    /**
     * Status
     *
     * 状态
     */
    status?: string | null;
};

/**
 * KnowledgeDocumentOut
 *
 * 知识库文档输出
 */
export type KnowledgeDocumentOut = {
    /**
     * Id
     *
     * 文档ID
     */
    id: string;
    /**
     * Knowledgebaseid
     *
     * 知识库ID
     */
    knowledgeBaseId: string;
    /**
     * Filename
     *
     * 文件名
     */
    fileName: string;
    /**
     * Filetype
     *
     * 文件类型
     */
    fileType: string;
    /**
     * Filesize
     *
     * 文件大小
     */
    fileSize: number;
    /**
     * Fileurl
     *
     * 文件地址
     */
    fileUrl: string;
    /**
     * Status
     *
     * 处理状态
     */
    status: string;
    /**
     * Chunkcount
     *
     * 片段数
     */
    chunkCount: number;
    /**
     * Createdat
     *
     * 创建时间
     */
    createdAt: string;
    /**
     * Updatedat
     *
     * 更新时间
     */
    updatedAt: string;
};

/**
 * LlmConfigCreateIn
 *
 * 创建LLM配置
 */
export type LlmConfigCreateIn = {
    /**
     * Name
     *
     * 配置名称
     */
    name: string;
    /**
     * Provider
     *
     * 服务商
     */
    provider: string;
    /**
     * Model
     *
     * 模型名称
     */
    model: string;
    /**
     * Baseurl
     *
     * 自定义 base_url
     */
    baseUrl?: string | null;
    /**
     * Isactive
     *
     * 是否设为活跃配置
     */
    isActive?: boolean;
};

/**
 * LlmConfigOut
 *
 * 用户LLM配置输出
 */
export type LlmConfigOut = {
    /**
     * Id
     *
     * 配置ID
     */
    id: string;
    /**
     * Userid
     *
     * 用户ID
     */
    userId: string;
    /**
     * Name
     *
     * 配置名称
     */
    name: string;
    /**
     * Provider
     *
     * 服务商
     */
    provider: string;
    /**
     * Model
     *
     * 模型名称
     */
    model: string;
    /**
     * Baseurl
     *
     * 自定义 base_url
     */
    baseUrl?: string | null;
    /**
     * Isactive
     *
     * 是否为活跃配置
     */
    isActive: boolean;
};

/**
 * LlmConfigUpdateIn
 *
 * 更新LLM配置
 */
export type LlmConfigUpdateIn = {
    /**
     * Name
     *
     * 配置名称
     */
    name?: string | null;
    /**
     * Provider
     *
     * 服务商
     */
    provider?: string | null;
    /**
     * Model
     *
     * 模型名称
     */
    model?: string | null;
    /**
     * Baseurl
     *
     * 自定义 base_url
     */
    baseUrl?: string | null;
    /**
     * Isactive
     *
     * 是否设为活跃配置
     */
    isActive?: boolean | null;
};

/**
 * LoginIn
 *
 * 登录请求体
 */
export type LoginIn = {
    /**
     * Email
     *
     * 登录邮箱
     */
    email: string;
    /**
     * Password
     *
     * 密码
     */
    password: string;
};

/**
 * LoginOut
 *
 * 登录响应体
 */
export type LoginOut = {
    /**
     * Accesstoken
     *
     * 验证令牌
     */
    accessToken: string;
    /**
     * Tokentype
     *
     * 令牌类型
     */
    tokenType?: string;
    /**
     * Expiresin
     *
     * 过期时长
     */
    expiresIn: number;
    /**
     * Refreshtoken
     *
     * 刷新令牌
     */
    refreshToken: string;
    /**
     * 用户信息
     */
    user: UserDetailOut;
};

/**
 * LogoutIn
 *
 * 登出请求体
 */
export type LogoutIn = {
    /**
     * Refreshtoken
     *
     * 刷新令牌
     */
    refreshToken: string;
};

/**
 * PaginatedResponse[CharacterListItemOut]
 */
export type PaginatedResponseCharacterListItemOut = {
    /**
     * Items
     */
    items: Array<CharacterListItemOut>;
    /**
     * Total
     *
     * 总条数
     */
    total: number;
    /**
     * Page
     *
     * 当前页码
     */
    page: number;
    /**
     * Page Size
     *
     * 每页条数
     */
    page_size: number;
    /**
     * Total Pages
     *
     * 总页数
     */
    total_pages: number;
};

/**
 * PaginatedResponse[ChatMessageOut]
 */
export type PaginatedResponseChatMessageOut = {
    /**
     * Items
     */
    items: Array<ChatMessageOut>;
    /**
     * Total
     *
     * 总条数
     */
    total: number;
    /**
     * Page
     *
     * 当前页码
     */
    page: number;
    /**
     * Page Size
     *
     * 每页条数
     */
    page_size: number;
    /**
     * Total Pages
     *
     * 总页数
     */
    total_pages: number;
};

/**
 * PaginatedResponse[ChatOut]
 */
export type PaginatedResponseChatOut = {
    /**
     * Items
     */
    items: Array<ChatOut>;
    /**
     * Total
     *
     * 总条数
     */
    total: number;
    /**
     * Page
     *
     * 当前页码
     */
    page: number;
    /**
     * Page Size
     *
     * 每页条数
     */
    page_size: number;
    /**
     * Total Pages
     *
     * 总页数
     */
    total_pages: number;
};

/**
 * PaginatedResponse[KnowledgeBaseOut]
 */
export type PaginatedResponseKnowledgeBaseOut = {
    /**
     * Items
     */
    items: Array<KnowledgeBaseOut>;
    /**
     * Total
     *
     * 总条数
     */
    total: number;
    /**
     * Page
     *
     * 当前页码
     */
    page: number;
    /**
     * Page Size
     *
     * 每页条数
     */
    page_size: number;
    /**
     * Total Pages
     *
     * 总页数
     */
    total_pages: number;
};

/**
 * PaginatedResponse[UserOut]
 */
export type PaginatedResponseUserOut = {
    /**
     * Items
     */
    items: Array<UserOut>;
    /**
     * Total
     *
     * 总条数
     */
    total: number;
    /**
     * Page
     *
     * 当前页码
     */
    page: number;
    /**
     * Page Size
     *
     * 每页条数
     */
    page_size: number;
    /**
     * Total Pages
     *
     * 总页数
     */
    total_pages: number;
};

/**
 * RequestResetPasswordIn
 */
export type RequestResetPasswordIn = {
    /**
     * Email
     */
    email: string;
};

/**
 * ResetPasswordIn
 */
export type ResetPasswordIn = {
    /**
     * Identifier
     *
     * 识别码
     */
    identifier: string;
    /**
     * Identitytype
     *
     * 认证类型
     */
    identityType: string;
    /**
     * Newpassword
     *
     * 新密码
     */
    newPassword: string;
    /**
     * Otp
     *
     * 验证码
     */
    otp: string;
};

/**
 * TokenOut
 *
 * 令牌响应体
 */
export type TokenOut = {
    /**
     * Accesstoken
     *
     * 验证令牌
     */
    accessToken: string;
    /**
     * Tokentype
     *
     * 令牌类型
     */
    tokenType?: string;
    /**
     * Expiresin
     *
     * 过期时长
     */
    expiresIn: number;
    /**
     * Refreshtoken
     *
     * 刷新令牌
     */
    refreshToken: string;
};

/**
 * TokenRefreshIn
 *
 * 刷新令牌请求体
 */
export type TokenRefreshIn = {
    /**
     * Refreshtoken
     *
     * 刷新令牌
     */
    refreshToken: string;
};

/**
 * UserAdminUpdateIn
 *
 * 管理员修改用户状态/角色
 */
export type UserAdminUpdateIn = {
    /**
     * Status
     *
     * 用户状态
     */
    status?: 'active' | 'inactive' | 'banned' | null;
    /**
     * Roleids
     *
     * 角色ID列表
     */
    roleIds?: Array<number>;
};

/**
 * UserDetailOut
 *
 * 完整的用户信息（包含账户状态+个人资料）
 */
export type UserDetailOut = {
    /**
     * Id
     *
     * 用户ID
     */
    id: string;
    /**
     * Status
     *
     * 用户状态
     */
    status: 'active' | 'inactive' | 'banned';
    /**
     * Roles
     *
     * 用户角色列表
     */
    roles: Array<string>;
    /**
     * Createdat
     *
     * 创建时间
     */
    createdAt: string;
    /**
     * Updatedat
     *
     * 更新时间
     */
    updatedAt: string;
    /**
     * Name
     *
     * 用户名
     */
    name: string;
    /**
     * Avatar
     *
     * 头像
     */
    avatar: string;
};

/**
 * UserOut
 *
 * 用户账户核心信息
 */
export type UserOut = {
    /**
     * Id
     *
     * 用户ID
     */
    id: string;
    /**
     * Status
     *
     * 用户状态
     */
    status: 'active' | 'inactive' | 'banned';
    /**
     * Roles
     *
     * 用户角色列表
     */
    roles: Array<string>;
    /**
     * Createdat
     *
     * 创建时间
     */
    createdAt: string;
    /**
     * Updatedat
     *
     * 更新时间
     */
    updatedAt: string;
};

/**
 * UserPublicOut
 *
 * 公开的用户资料
 */
export type UserPublicOut = {
    /**
     * Id
     *
     * 用户ID
     */
    id: string;
    /**
     * Name
     *
     * 用户名
     */
    name: string;
    /**
     * Avatar
     *
     * 用户头像
     */
    avatar: string;
    /**
     * Createdat
     *
     * 创建时间
     */
    createdAt: string;
};

/**
 * UserUpdateIn
 *
 * 修改个人资料
 */
export type UserUpdateIn = {
    /**
     * Name
     *
     * 用户名
     */
    name?: string | null;
    /**
     * Avatar
     *
     * 头像
     */
    avatar?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type RegisterByEmailData = {
    body: EmailRegisterIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register/email';
};

export type RegisterByEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterByEmailError = RegisterByEmailErrors[keyof RegisterByEmailErrors];

export type RegisterByEmailResponses = {
    /**
     * Successful Response
     */
    201: ApiResponseAuthOut;
};

export type RegisterByEmailResponse = RegisterByEmailResponses[keyof RegisterByEmailResponses];

export type LoginData = {
    body: LoginIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseLoginOut;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body: LogoutIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type RefreshData = {
    body: TokenRefreshIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/token/refresh';
};

export type RefreshErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseTokenOut;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type RequestEmailVerificationData = {
    body: EmailVerifyRequestIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/email-verification/request';
};

export type RequestEmailVerificationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequestEmailVerificationError = RequestEmailVerificationErrors[keyof RequestEmailVerificationErrors];

export type RequestEmailVerificationResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type RequestEmailVerificationResponse = RequestEmailVerificationResponses[keyof RequestEmailVerificationResponses];

export type VerifyEmailData = {
    body: EmailVerifyConfirmIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/email-verification/verify';
};

export type VerifyEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyEmailError = VerifyEmailErrors[keyof VerifyEmailErrors];

export type VerifyEmailResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type VerifyEmailResponse = VerifyEmailResponses[keyof VerifyEmailResponses];

export type RequestPasswordResetData = {
    body: RequestResetPasswordIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/password-reset/request';
};

export type RequestPasswordResetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequestPasswordResetError = RequestPasswordResetErrors[keyof RequestPasswordResetErrors];

export type RequestPasswordResetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type RequestPasswordResetResponse = RequestPasswordResetResponses[keyof RequestPasswordResetResponses];

export type VerifyPasswordResetData = {
    body: ResetPasswordIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/password-reset/confirm';
};

export type VerifyPasswordResetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyPasswordResetError = VerifyPasswordResetErrors[keyof VerifyPasswordResetErrors];

export type VerifyPasswordResetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type VerifyPasswordResetResponse = VerifyPasswordResetResponses[keyof VerifyPasswordResetResponses];

export type ListSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sessions';
};

export type ListSessionsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteSessionData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/auth/sessions/{session_id}';
};

export type DeleteSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSessionError = DeleteSessionErrors[keyof DeleteSessionErrors];

export type DeleteSessionResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteAllSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sessions/others';
};

export type DeleteAllSessionsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChangePasswordData = {
    body: ChangePasswordIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/password/change';
};

export type ChangePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type SetupOtpData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/2fa/otp/setup';
};

export type SetupOtpResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type EnableOtpData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/2fa/otp/enable';
};

export type EnableOtpResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DisableOtpData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/2fa/otp/disable';
};

export type DisableOtpResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type VerifyOtpData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/2fa/otp/verify';
};

export type VerifyOtpResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type OauthAuthorizeData = {
    body?: never;
    path: {
        /**
         * Provider
         */
        provider: string;
    };
    query?: never;
    url: '/api/v1/auth/oauth/{provider}/authorize';
};

export type OauthAuthorizeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OauthAuthorizeError = OauthAuthorizeErrors[keyof OauthAuthorizeErrors];

export type OauthAuthorizeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type OauthCallbackData = {
    body?: never;
    path: {
        /**
         * Provider
         */
        provider: string;
    };
    query?: never;
    url: '/api/v1/auth/oauth/{provider}/callback';
};

export type OauthCallbackErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OauthCallbackError = OauthCallbackErrors[keyof OauthCallbackErrors];

export type OauthCallbackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UnlinkOauthAccountData = {
    body?: never;
    path: {
        /**
         * Provider
         */
        provider: string;
    };
    query?: never;
    url: '/api/v1/auth/oauth/{provider}/unlink';
};

export type UnlinkOauthAccountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnlinkOauthAccountError = UnlinkOauthAccountErrors[keyof UnlinkOauthAccountErrors];

export type UnlinkOauthAccountResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCurrentAuthUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetCurrentAuthUserResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseUserDetailOut;
};

export type GetCurrentAuthUserResponse = GetCurrentAuthUserResponses[keyof GetCurrentAuthUserResponses];

export type DeleteAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/account';
};

export type DeleteAccountResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type GetAuditLogsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/audit-logs';
};

export type GetAuditLogsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCharactersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Keyword
         */
        keyword?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/characters';
};

export type GetCharactersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCharactersError = GetCharactersErrors[keyof GetCharactersErrors];

export type GetCharactersResponses = {
    /**
     * Successful Response
     */
    200: ApiResponsePaginatedResponseCharacterListItemOut;
};

export type GetCharactersResponse = GetCharactersResponses[keyof GetCharactersResponses];

export type CreateCharacterData = {
    body: CharacterCreateIn;
    path?: never;
    query?: never;
    url: '/api/v1/characters';
};

export type CreateCharacterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCharacterError = CreateCharacterErrors[keyof CreateCharacterErrors];

export type CreateCharacterResponses = {
    /**
     * Successful Response
     */
    201: ApiResponseCharacterDetailOut;
};

export type CreateCharacterResponse = CreateCharacterResponses[keyof CreateCharacterResponses];

export type GetFavoriteCharactersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/characters/favorites';
};

export type GetFavoriteCharactersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFavoriteCharactersError = GetFavoriteCharactersErrors[keyof GetFavoriteCharactersErrors];

export type GetFavoriteCharactersResponses = {
    /**
     * Successful Response
     */
    200: ApiResponsePaginatedResponseCharacterListItemOut;
};

export type GetFavoriteCharactersResponse = GetFavoriteCharactersResponses[keyof GetFavoriteCharactersResponses];

export type DeleteCharacterData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/characters/{id}';
};

export type DeleteCharacterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCharacterError = DeleteCharacterErrors[keyof DeleteCharacterErrors];

export type DeleteCharacterResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type DeleteCharacterResponse = DeleteCharacterResponses[keyof DeleteCharacterResponses];

export type GetPublicCharacterData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/characters/{id}';
};

export type GetPublicCharacterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPublicCharacterError = GetPublicCharacterErrors[keyof GetPublicCharacterErrors];

export type GetPublicCharacterResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseCharacterDetailOut;
};

export type GetPublicCharacterResponse = GetPublicCharacterResponses[keyof GetPublicCharacterResponses];

export type UpdateCharacterData = {
    body: CharacterUpdateIn;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/characters/{id}';
};

export type UpdateCharacterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCharacterError = UpdateCharacterErrors[keyof UpdateCharacterErrors];

export type UpdateCharacterResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseCharacterDetailOut;
};

export type UpdateCharacterResponse = UpdateCharacterResponses[keyof UpdateCharacterResponses];

export type GetPrivateCharacterData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/characters/{id}/private';
};

export type GetPrivateCharacterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPrivateCharacterError = GetPrivateCharacterErrors[keyof GetPrivateCharacterErrors];

export type GetPrivateCharacterResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseCharacterDetailOut;
};

export type GetPrivateCharacterResponse = GetPrivateCharacterResponses[keyof GetPrivateCharacterResponses];

export type CancelFavoriteCharacterData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/characters/{id}/favorite';
};

export type CancelFavoriteCharacterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelFavoriteCharacterError = CancelFavoriteCharacterErrors[keyof CancelFavoriteCharacterErrors];

export type CancelFavoriteCharacterResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type CancelFavoriteCharacterResponse = CancelFavoriteCharacterResponses[keyof CancelFavoriteCharacterResponses];

export type FavoriteCharacterData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/characters/{id}/favorite';
};

export type FavoriteCharacterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FavoriteCharacterError = FavoriteCharacterErrors[keyof FavoriteCharacterErrors];

export type FavoriteCharacterResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type FavoriteCharacterResponse = FavoriteCharacterResponses[keyof FavoriteCharacterResponses];

export type ListCharacterKnowledgeBasesData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/characters/{id}/knowledge-bases';
};

export type ListCharacterKnowledgeBasesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListCharacterKnowledgeBasesError = ListCharacterKnowledgeBasesErrors[keyof ListCharacterKnowledgeBasesErrors];

export type ListCharacterKnowledgeBasesResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListKnowledgeBaseOut;
};

export type ListCharacterKnowledgeBasesResponse = ListCharacterKnowledgeBasesResponses[keyof ListCharacterKnowledgeBasesResponses];

export type BindKnowledgeBaseData = {
    body: BindKnowledgeBaseIn;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/characters/{id}/knowledge-bases';
};

export type BindKnowledgeBaseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BindKnowledgeBaseError = BindKnowledgeBaseErrors[keyof BindKnowledgeBaseErrors];

export type BindKnowledgeBaseResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type BindKnowledgeBaseResponse = BindKnowledgeBaseResponses[keyof BindKnowledgeBaseResponses];

export type UnbindKnowledgeBaseData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
        /**
         * Kb Id
         */
        kb_id: string;
    };
    query?: never;
    url: '/api/v1/characters/{id}/knowledge-bases/{kb_id}';
};

export type UnbindKnowledgeBaseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnbindKnowledgeBaseError = UnbindKnowledgeBaseErrors[keyof UnbindKnowledgeBaseErrors];

export type UnbindKnowledgeBaseResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type UnbindKnowledgeBaseResponse = UnbindKnowledgeBaseResponses[keyof UnbindKnowledgeBaseResponses];

export type ListMyChatsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/chats';
};

export type ListMyChatsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMyChatsError = ListMyChatsErrors[keyof ListMyChatsErrors];

export type ListMyChatsResponses = {
    /**
     * Successful Response
     */
    200: ApiResponsePaginatedResponseChatOut;
};

export type ListMyChatsResponse = ListMyChatsResponses[keyof ListMyChatsResponses];

export type CreateChatData = {
    body: ChatCreateIn;
    path?: never;
    query?: never;
    url: '/api/v1/chats';
};

export type CreateChatErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateChatError = CreateChatErrors[keyof CreateChatErrors];

export type CreateChatResponses = {
    /**
     * Successful Response
     */
    201: ApiResponseChatOut;
};

export type CreateChatResponse = CreateChatResponses[keyof CreateChatResponses];

export type DeleteChatData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/chats/{id}';
};

export type DeleteChatErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteChatError = DeleteChatErrors[keyof DeleteChatErrors];

export type DeleteChatResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type DeleteChatResponse = DeleteChatResponses[keyof DeleteChatResponses];

export type GetChatData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/chats/{id}';
};

export type GetChatErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChatError = GetChatErrors[keyof GetChatErrors];

export type GetChatResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseChatOut;
};

export type GetChatResponse = GetChatResponses[keyof GetChatResponses];

export type UpdateChatData = {
    body: ChatUpdateIn;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/chats/{id}';
};

export type UpdateChatErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateChatError = UpdateChatErrors[keyof UpdateChatErrors];

export type UpdateChatResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseChatOut;
};

export type UpdateChatResponse = UpdateChatResponses[keyof UpdateChatResponses];

export type ListMessagesData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/chats/{id}/messages';
};

export type ListMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMessagesError = ListMessagesErrors[keyof ListMessagesErrors];

export type ListMessagesResponses = {
    /**
     * Successful Response
     */
    200: ApiResponsePaginatedResponseChatMessageOut;
};

export type ListMessagesResponse = ListMessagesResponses[keyof ListMessagesResponses];

export type SendMessageData = {
    body: ChatMessageCreateIn;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/chats/{id}/messages';
};

export type SendMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendMessageError = SendMessageErrors[keyof SendMessageErrors];

export type SendMessageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RegenerateMessageData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
        /**
         * Message Id
         */
        message_id: string;
    };
    query?: never;
    url: '/api/v1/chats/{id}/messages/{message_id}/regenerate';
};

export type RegenerateMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegenerateMessageError = RegenerateMessageErrors[keyof RegenerateMessageErrors];

export type RegenerateMessageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListKbsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Keyword
         */
        keyword?: string | null;
    };
    url: '/api/v1/knowledge-bases';
};

export type ListKbsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListKbsError = ListKbsErrors[keyof ListKbsErrors];

export type ListKbsResponses = {
    /**
     * Successful Response
     */
    200: ApiResponsePaginatedResponseKnowledgeBaseOut;
};

export type ListKbsResponse = ListKbsResponses[keyof ListKbsResponses];

export type CreateKbData = {
    body: KnowledgeBaseCreateIn;
    path?: never;
    query?: never;
    url: '/api/v1/knowledge-bases';
};

export type CreateKbErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateKbError = CreateKbErrors[keyof CreateKbErrors];

export type CreateKbResponses = {
    /**
     * Successful Response
     */
    201: ApiResponseKnowledgeBaseOut;
};

export type CreateKbResponse = CreateKbResponses[keyof CreateKbResponses];

export type DeleteKbData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/knowledge-bases/{id}';
};

export type DeleteKbErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteKbError = DeleteKbErrors[keyof DeleteKbErrors];

export type DeleteKbResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type DeleteKbResponse = DeleteKbResponses[keyof DeleteKbResponses];

export type GetKbData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/knowledge-bases/{id}';
};

export type GetKbErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetKbError = GetKbErrors[keyof GetKbErrors];

export type GetKbResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseKnowledgeBaseOut;
};

export type GetKbResponse = GetKbResponses[keyof GetKbResponses];

export type UpdateKbData = {
    body: KnowledgeBaseUpdateIn;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/knowledge-bases/{id}';
};

export type UpdateKbErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateKbError = UpdateKbErrors[keyof UpdateKbErrors];

export type UpdateKbResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseKnowledgeBaseOut;
};

export type UpdateKbResponse = UpdateKbResponses[keyof UpdateKbResponses];

export type UploadDocumentData = {
    body: BodyUploadDocument;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/knowledge-bases/{id}/upload';
};

export type UploadDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadDocumentError = UploadDocumentErrors[keyof UploadDocumentErrors];

export type UploadDocumentResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseKnowledgeDocumentOut;
};

export type UploadDocumentResponse = UploadDocumentResponses[keyof UploadDocumentResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseUserDetailOut;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type UpdateCurrentUserData = {
    body: UserUpdateIn;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateCurrentUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCurrentUserError = UpdateCurrentUserErrors[keyof UpdateCurrentUserErrors];

export type UpdateCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseUserDetailOut;
};

export type UpdateCurrentUserResponse = UpdateCurrentUserResponses[keyof UpdateCurrentUserResponses];

export type GetPublicUserData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type GetPublicUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPublicUserError = GetPublicUserErrors[keyof GetPublicUserErrors];

export type GetPublicUserResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseUserPublicOut;
};

export type GetPublicUserResponse = GetPublicUserResponses[keyof GetPublicUserResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/users';
};

export type ListUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    /**
     * Successful Response
     */
    200: ApiResponsePaginatedResponseUserOut;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type AdminUpdateUserData = {
    body: UserAdminUpdateIn;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}/admin';
};

export type AdminUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminUpdateUserError = AdminUpdateUserErrors[keyof AdminUpdateUserErrors];

export type AdminUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseUserOut;
};

export type AdminUpdateUserResponse = AdminUpdateUserResponses[keyof AdminUpdateUserResponses];

export type ListMyLlmConfigsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/llm-configs';
};

export type ListMyLlmConfigsResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListLlmConfigOut;
};

export type ListMyLlmConfigsResponse = ListMyLlmConfigsResponses[keyof ListMyLlmConfigsResponses];

export type CreateLlmConfigData = {
    body: LlmConfigCreateIn;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/llm-configs';
};

export type CreateLlmConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLlmConfigError = CreateLlmConfigErrors[keyof CreateLlmConfigErrors];

export type CreateLlmConfigResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseLlmConfigOut;
};

export type CreateLlmConfigResponse = CreateLlmConfigResponses[keyof CreateLlmConfigResponses];

export type DeleteLlmConfigData = {
    body?: never;
    path: {
        /**
         * Config Id
         */
        config_id: string;
    };
    query?: never;
    url: '/api/v1/users/me/llm-configs/{config_id}';
};

export type DeleteLlmConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteLlmConfigError = DeleteLlmConfigErrors[keyof DeleteLlmConfigErrors];

export type DeleteLlmConfigResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type DeleteLlmConfigResponse = DeleteLlmConfigResponses[keyof DeleteLlmConfigResponses];

export type UpdateLlmConfigData = {
    body: LlmConfigUpdateIn;
    path: {
        /**
         * Config Id
         */
        config_id: string;
    };
    query?: never;
    url: '/api/v1/users/me/llm-configs/{config_id}';
};

export type UpdateLlmConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateLlmConfigError = UpdateLlmConfigErrors[keyof UpdateLlmConfigErrors];

export type UpdateLlmConfigResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseLlmConfigOut;
};

export type UpdateLlmConfigResponse = UpdateLlmConfigResponses[keyof UpdateLlmConfigResponses];
